rem  INSERT Car Data (17개 모델, 옵션 포함)
INSERT INTO Car VALUES ('CAR001', 'Avante', 'Sedan', 'B');
INSERT INTO Car VALUES ('CAR001', 'Avante', 'Sedan', 'P');
INSERT INTO Car VALUES ('CAR002', 'Sonata', 'Sedan', 'B');
INSERT INTO Car VALUES ('CAR002', 'Sonata', 'Sedan', 'P');
INSERT INTO Car VALUES ('CAR003', 'Grandeur', 'Sedan', 'B');
INSERT INTO Car VALUES ('CAR003', 'Grandeur', 'Sedan', 'P');
INSERT INTO Car VALUES ('CAR004', 'G70', 'Sedan', 'B');
INSERT INTO Car VALUES ('CAR004', 'G70', 'Sedan', 'P');
INSERT INTO Car VALUES ('CAR005', 'G80', 'Sedan', 'B');
INSERT INTO Car VALUES ('CAR005', 'G80', 'Sedan', 'P');
INSERT INTO Car VALUES ('CAR006', 'G90', 'Sedan', 'B');
INSERT INTO Car VALUES ('CAR006', 'G90', 'Sedan', 'P');
INSERT INTO Car VALUES ('CAR007', 'Palisade', 'SUV', 'B');
INSERT INTO Car VALUES ('CAR007', 'Palisade', 'SUV', 'P');
INSERT INTO Car VALUES ('CAR008', 'Tucson', 'SUV', 'B');
INSERT INTO Car VALUES ('CAR008', 'Tucson', 'SUV', 'P');
INSERT INTO Car VALUES ('CAR009', 'Venue', 'SUV', 'B');
INSERT INTO Car VALUES ('CAR009', 'Venue', 'SUV', 'P');
INSERT INTO Car VALUES ('CAR010', 'Kona', 'SUV', 'B');
INSERT INTO Car VALUES ('CAR010', 'Kona', 'SUV', 'P');
INSERT INTO Car VALUES ('CAR011', 'Santa Fe', 'SUV', 'B');
INSERT INTO Car VALUES ('CAR011', 'Santa Fe', 'SUV', 'P');
INSERT INTO Car VALUES ('CAR012', 'GV70', 'SUV', 'B');
INSERT INTO Car VALUES ('CAR012', 'GV70', 'SUV', 'P');
INSERT INTO Car VALUES ('CAR013', 'GV80', 'SUV', 'B');
INSERT INTO Car VALUES ('CAR013', 'GV80', 'SUV', 'P');
INSERT INTO Car VALUES ('CAR014', 'Staria', 'Compact', 'B');
INSERT INTO Car VALUES ('CAR014', 'Staria', 'Compact', 'P');
INSERT INTO Car VALUES ('CAR015', 'GV60', 'Electric', 'B');
INSERT INTO Car VALUES ('CAR015', 'GV60', 'Electric', 'P');
INSERT INTO Car VALUES ('CAR016', 'Ioniq 6', 'Electric', 'B');
INSERT INTO Car VALUES ('CAR016', 'Ioniq 6', 'Electric', 'P');
INSERT INTO Car VALUES ('CAR017', 'Ioniq 5', 'Electric', 'B');
INSERT INTO Car VALUES ('CAR017', 'Ioniq 5', 'Electric', 'P');
