INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR001', '{"Name": "Avante", "Type": "Sedan", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR001', '{"Name": "Avante", "Type": "Sedan", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR002', '{"Name": "Sonata", "Type": "Sedan", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR002', '{"Name": "Sonata", "Type": "Sedan", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR003', '{"Name": "Grandeur", "Type": "Sedan", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR003', '{"Name": "Grandeur", "Type": "Sedan", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR004', '{"Name": "G70", "Type": "Sedan", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR004', '{"Name": "G70", "Type": "Sedan", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR005', '{"Name": "G80", "Type": "Sedan", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR005', '{"Name": "G80", "Type": "Sedan", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR006', '{"Name": "G90", "Type": "Sedan", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR006', '{"Name": "G90", "Type": "Sedan", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR007', '{"Name": "Palisade", "Type": "SUV", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR007', '{"Name": "Palisade", "Type": "SUV", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR008', '{"Name": "Tucson", "Type": "SUV", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR008', '{"Name": "Tucson", "Type": "SUV", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR009', '{"Name": "Venue", "Type": "SUV", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR009', '{"Name": "Venue", "Type": "SUV", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR010', '{"Name": "Kona", "Type": "SUV", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR010', '{"Name": "Kona", "Type": "SUV", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR011', '{"Name": "Santa Fe", "Type": "SUV", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR011', '{"Name": "Santa Fe", "Type": "SUV", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR012', '{"Name": "GV70", "Type": "SUV", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR012', '{"Name": "GV70", "Type": "SUV", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR013', '{"Name": "GV80", "Type": "SUV", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR013', '{"Name": "GV80", "Type": "SUV", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR014', '{"Name": "Staria", "Type": "Compact", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR014', '{"Name": "Staria", "Type": "Compact", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR015', '{"Name": "GV60", "Type": "Electric", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR015', '{"Name": "GV60", "Type": "Electric", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR016', '{"Name": "Ioniq 6", "Type": "Electric", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR016', '{"Name": "Ioniq 6", "Type": "Electric", "Option": "P"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR017', '{"Name": "Ioniq 5", "Type": "Electric", "Option": "B"}');
INSERT INTO Car (Car_ID, jsonstr) VALUES ('CAR017', '{"Name": "Ioniq 5", "Type": "Electric", "Option": "P"}');