-- DROP TALBE
DROP TABLE CAR;
DROP TABLE CUSTOMER;
DROP TABLE BRANCH;
DROP TABLE EMPLOYEE;

-- CREATE TABLE
-- CAR 테이블 생성
CREATE TABLE CAR (
    Car_ID VARCHAR2(10) NOT NULL,
    Car_Name VARCHAR2(100) NOT NULL,
    Car_Type VARCHAR2(100) NOT NULL,
    Car_Option VARCHAR2(100),
    CONSTRAINT PK_CAR_id PRIMARY KEY (Car_ID)
);

-- CUSTOMER 테이블 생성
CREATE TABLE CUSTOMER (
    Cust_ID VARCHAR2(10) NOT NULL,
    Cust_Name VARCHAR2(100) NOT NULL,
    Cust_Birth_Date DATE,
    Cust_Email VARCHAR2(50),
    Cust_Status VARCHAR2(10),
    Cust_Update_Date DATE,
    Cust_Address VARCHAR2(100),
    Cust_Phone VARCHAR2(25),
    Cust_Type VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (Cust_ID),
    CONSTRAINT UQ_CUSTOMER_st UNIQUE (Cust_Status)
);

-- BRANCH 테이블 생성
CREATE TABLE BRANCH (
    Branch_Id VARCHAR2(10) NOT NULL,
    Branch_Name VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_BRANCH PRIMARY KEY (Branch_Id)
);

-- EMPLOYEE 테이블 생성
CREATE TABLE EMPLOYEE (
    Emp_Id VARCHAR2(10) NOT NULL,
    Emp_Name VARCHAR2(100) NOT NULL,
    Email_Address VARCHAR2(100),
    Emp_Pwd VARCHAR2(100) NOT NULL,
    Emp_Phone VARCHAR2(25),
    Emp_Position VARCHAR2(100),
    Branch_Id VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Emp_Id),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (Branch_Id) REFERENCES BRANCH(Branch_Id)
);