DROP TRIGGER EMPLOYEE_TRG;

DROP SEQUENCE EMP_SEQ;

DROP TRIGGER CUSTOMER_TRG;

DROP SEQUENCE CUST_SEQ;

DROP TRIGGER PURCHASE_TRG;

DROP SEQUENCE PUR_SEQ;

DROP TRIGGER COMPLAIN_TRG;

DROP SEQUENCE COMP_SEQ;
   
CREATE SEQUENCE EMP_SEQ
    START WITH 25
    INCREMENT BY 1
    NOCACHE;

-- 트리거 생성
CREATE OR REPLACE TRIGGER EMPLOYEE_TRG
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
BEGIN
    IF :NEW.Emp_Id IS NULL THEN
        :NEW.Emp_Id := EMP_SEQ.NEXTVAL;
    END IF;
END;

CREATE SEQUENCE CUST_SEQ
    START WITH 51
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER CUSTOMER_TRG
    BEFORE INSERT ON CUSTOMER
    FOR EACH ROW
BEGIN
    IF :NEW.Cust_Id IS NULL THEN
        :NEW.Cust_Id := CUST_SEQ.NEXTVAL;
    END IF;
END;
	
CREATE SEQUENCE PUR_SEQ
    START WITH 186
    INCREMENT BY 1
    NOCACHE;

-- 트리거 생성
CREATE OR REPLACE TRIGGER PURCHASE_TRG
    BEFORE INSERT ON PURCHASE
    FOR EACH ROW
BEGIN
    IF :NEW.SALE_ID IS NULL THEN
        :NEW.SALE_ID := PUR_SEQ.NEXTVAL;
    END IF;
END;

CREATE SEQUENCE COMP_SEQ;
   START WiTH 10
   INCREMENT BY 1
   NOCACHE;
   
CREATE OR REPLACE TRIGGER COMPLAIN_TRG
   BEFORE INSERT ON COMPLAIN
   FOR EACH ROW
BEGIN
   IF :NEW.COMP_ID IS NULL THEN
      :NEW.COMP_ID := COMP_SEQ.NEXTVAL;
   END IF;
END;
